### ISSUE TITLE
.env does not exist

### ISSUE THREAD

**Issue by oa98105** [gfhuertac/maka#3]
Hi 
Since I do not have .env so I just copied the key in inquirer.py
 headers = {
            'user-agent': AcademicConf.USER_AGENT,
            'Ocp-Apim-Subscription-Key': my here 
}
but I am getting following error. Could you also please elaborate where usually is this .env directory found in linux
/usr/local/lib/python2.7/dist-packages/dotenv/main.py:24: UserWarning: Not loading samples/.env - it doesn't exist.
  warnings.warn("Not loading %s - it doesn't exist." % dotenv_path)
Worker 0: Looking for the next query
Worker 1: Looking for the next query
 *** Main thread waiting
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "samples/author.py", line 57, in querier_enclosure
    results = query.post()
  File "/home/oa/PythonCodes/maka/inquirer.py", line 423, in post
    .format(the_request.status_code))
Error: An error ocurred while processing the request. Code: 401

**Comment by gfhuertac** [comment]
Hi, This is explained in the samples section:
"To run the samples first you need to copy the file env.sample to .env and modify it to add your Microsoft's Cognitive service key"
So, go to the samples folder, copy env.sample to .env and modify it to reflect your credentials.

**Comment by oa98105** [comment]
Hi,
Thanks for your feedback. Actually I do not have .env folder in my environment. Could you pinpoint where should i create it to run your code. Or where I may change the code directly to use hard coded values.
Thanks

**Comment by oa98105** [comment]
Ok thanks ignore my last message
I just created a directory .env under samples and copied env.sample in .env and also changed a line in the code 
dotenv_path = join(dirname(__file__), '.env/env.sample')

**Comment by gfhuertac** [comment]
Glad that you made it work.
Just notice that there is no need to create a .env folder, you just need to rename the file env.sample to .env :)
