### ISSUE TITLE
interpret and evaluate

### ISSUE THREAD

**Issue by oa98105** [gfhuertac/maka#4]
I checked on the dev.labs.cognitive.microsoft.com/docs/services/ if my key is working for the following request it works. The request is 
https://api.labs.cognitive.microsoft.com/academic/v1.0/interpret?query=Smart Refresh: An Enhanced Memory Controller Design for Reducing Energy in Conventional and 3D Die-Stacked DRAMs&complete=0&count=10&model=latest

I tired this python samples/author.py --author "albert einstein" which ends in 
 *** Main thread waiting
[DEBUG]  Received 
{"error":{"code":"Unspecified","message":"Access denied due to invalid subscription key. Make sure you are subscribed to an API you are trying to call and provide the right key."}}

On the website my key works for interpret and evaluate using their try it link. 

Also how I am going to write my actual request as above for your your code. like below
python samples/author.py --author "Smart Refresh: An Enhanced Memory Controller Design for Reducing Energy in Conventional and 3D Die-Stacked DRAMs"
Thanks

**Comment by gfhuertac** [comment]
That's related with your previous question.
Please delete the .env folder that you created, and just create a copy of the env.sample file and rename it .env (.env is a file, not a folder).
